### ISSUE TITLE
Can IDE model deal with irregular geostatistical data ?

### ISSUE THREAD

**Issue by stevenhuyi** [andrewzm/IDE#1]
Dear all,
I have a spatio-temporal data set  of 24-year human schistosomiasis prevalence at the village level, and the number of sample village are different in each year (which can be seen as geostatistical data), that is, some villages are surveyed each year while some villages are not. I would like to investigate dynamic pattern of the disease over my study area. It seems that IDE function only deal with spatiotemporal data with complete spatial coverage.  Any response will be appreciated!
Best
steven

**Comment by andrewzm** [comment]
Hi Steven,
  The IDE package can deal with spatio-temporal data that is not on a
regular grid (that is spatio-temporally irregular), not a problem. Look at
Lab 5.2 (Figure 5.4) in our book for such a case. It will need to be
assumed though that the villages are points (and not areas) as currently
the package does not support areal observations. Note also that you need a
good number of villages to reliably estimate dynamics. Hope this helps.

Regards,
Andrew

**Comment by stevenhuyi** [comment]
Hi Andrew, 
Thanks for your reply and the example you mentioned is helpful. Yes, villages are assumed to points in my study. However, I've encountered a problem when using IDE function to my data set. the codes are as follows:
IDEmodel<-IDE(f=p~1,
              data=myschist,
              dt=as.difftime(1,units = "days"),
              grid_size = 0.01)
the error is :  **Error in solve(crossprod(X_obs, X_obs)) %*% t(X_obs) %*% Z : 
  requires numeric/complex matrix/vector arguments**
I think it would be due to my data which contains lots of zero (as the schistosmiasis prevalence is low as a whole, but relatively high locally in my study area), which can be indicated as follows
summary(myschist@data$p)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.6046  0.7316 25.5760 
The number of villages in each time unit  are as follows, which I do not think as a reason as they are enough:
summary(with(mydata, table(time)))
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  64.00   89.75   99.50   99.17  112.25  128.00  
Is there a way around my problem, thanks.

Best
steven

**Comment by andrewzm** [comment]
Hi Steven,
  Please rename your dependent variable "p" to "z" for now. There is a bug
I need to fix I think, let me know if you get a different error, you should
at least be able to compile the model like this.

Andrew

**Comment by stevenhuyi** [comment]
Hi Andrew,
Thanks. There is still an error as follows when I change the response variable to "z":
`IDEmodel<-IDE(f=z~1,
              data=myschist,
              dt=as.difftime(1,units = "days"),
              grid_size = 0.01)`
> Error in 1:max(unique(batching)) : NA/NaN argument

steven

**Comment by andrewzm** [comment]
OK Steven -- can you send me your code and your data please? (You can put
random numbers in the z variable to mask the real data if you wish).

**Comment by stevenhuyi** [comment]
Done. Please check your gmail.

steven

**Comment by andrewzm** [comment]
Hi Steve,
  From the help file:

grid_size: an integer identifying the number of grid points to use (in one
dimension) for numerical integrations

So you need to replace 0.01 with something like 41. If you do that your
code works.

Regards,
Andrew


grid_size

an integer identifying the number of grid points to use (in one dimension)
for numerical integrations

**Comment by stevenhuyi** [comment]
Thanks, Andrew. It works.
Best
steven

**Comment by andrewzm** [comment]
Glad to hear!

**Comment by stevenhuyi** [comment]
Andrew,
A further issue: an error occurred  when I plot a varying kernel. the codes are as follows:

`mbasis_1 <- auto_basis(manifold = plane(), 
                       data = myschist, 
                       nres = 1, 
                       type = 'bisquare')

kernel_basis <- list(thetam1 = constant_basis(),
                     thetam2 = constant_basis(),
                     thetam3 = mbasis_1,
                     thetam4 = mbasis_1)

IDEmodel2 <- IDE(f = z ~ 1,
                data = myschist,
                dt = as.difftime(1, units = "days"),
                grid_size = 50,
                kernel_basis = kernel_basis)

fit_var <- fit.IDE(IDEmodel2, parallelType = 1)
show_kernel(fit_var,scale = 0.2)`

the error is: **Error in IDEmodel$get("kernel_basis") : attempt to apply non-function**

Here attached is the result of fit_var
[GC_varkerl.zip](https://github.com/andrewzm/IDE/files/3284435/GC_varkerl.zip)

Thanks.
steven

**Comment by andrewzm** [comment]
Hi Steven,
  The fit_var object contains the IDE model as well as the optim results so
you need to do

show_kernel(IDEmodel = fit_var$IDEmodel, scale = 0.1)

but I found a small bug which I fixed since you are using different
coordnames. Please update using

library(devtools)
install_github("andrewzm/IDE", dependencies = FALSE)

and then run show_kernel as above, and you should see the arrows.

Regards,
Andrew

**Comment by stevenhuyi** [comment]
Andrew,
Thanks so much for the instant reply every time. With your help, I've been familiar with the whole process of dealing with spatio-temporal data using the IDE package right row. I still, however, have some issues to discuss with you:
1. In the perspective of hierarchical modelling, the data level in IDE package seems to be assumed to have Gaussian distribution. This would be a limitation in disease data, which are more likely to have count data assumption (e.g., (negative) binomial, Poisson distribution). Take my schistosomiasis data set for example, R8 and R6 are number of the infected and population at risk, respectively. My ideal is that R8 is  assumed to be negative binomial distributed, rather than assuming the prevalence (i.e., R8/R6) to be Gaussian distributed.  Is this a consideration in your future version?
2. When fitting IDE model to spatio-temporal data, how to choose kernel type (I mean invariant or variant one) while the shifting trend is not clear from the  observations as shown in my schistosomiasis data. Just through the prediction error of each kernel type?
3. When any kernel type is set, the shifting direction can be obtained from the fitting results. What if we further want to know the shifting speed? Take varying kernel for example, how to calculate the shifting speed at very predicted location.

Best
Steven

**Comment by andrewzm** [comment]
Hi Steven,
  Glad you got it working -- the flow direction seemed to be consistently
in one direction, which is a good sign.

With regards to your questions:

1. Sorry only Gaussian for now. My other package FRK is also Gaussian-only
for now but we are working on providing several non-Gaussian likelihoods
via TMB. If that works well in the end we might look at putting that into
IDE.

2. Yes that's a good question, and I would approach it as a model selection
problem. Ultimately, if you don't have a lot of data, and the kernel is
very complex, you will overfit, as we are in a maximum likelihood setting.
One thing you can do is fit using an invariant kernel and a
spatially-varying kernel, on a subsets of the data, and verify which one is
better through cross-validation.

3. You should look at the code I use in the function show_kernel. There I
derive the velocities as follows:

 s$s_grid_df$hor <-  eval_basis(kernel_basis[[3]],s$s_grid_mat) %*% k[[3]]
%>% as.numeric()
 s$s_grid_df$ver <-  eval_basis(kernel_basis[[4]],s$s_grid_mat) %*% k[[4]]
%>% as.numeric()

where

   kernel_basis <- IDEmodel$get("kernel_basis")
   k <- IDEmodel$get("k")
   s <- IDEmodel$get("s")

This gives you the horizontal shift and vertical shift parameters at every
location in s$s_grid_mat, but really these can be any prediction locations
you want. To translate these into units of interest, e.g., km/hr, you just
need to know what time step you are using (e.g., 10 minutes) and the units
of space (e.g., metres or degrees).

The function eval_basis is imported from FRK, so to run that code outside
the IDE package you need something like FRK::eval_basis.

Hope this helps.

Regards,
Andrew

**Comment by stevenhuyi** [comment]
Hi Andrew,
Thanks again :) Further questions come out.

1. I'm still not sure about how to calculate the drifting speed when the invariant kernel after checking the code of show_kernel function. I think this speed is the same for all predicted location.

2. Can you show me how to calculate the uncertainties (e.g., the confidence interval) of all the parameters to be estimated, including the coefficients of covariates and kernel parameters.

3. There is still a bug in the IDE function, that is 
`IDEmodel2 <- IDE(f = p ~ 1,
                data = myschist,
                dt = as.difftime(1, units = "days"),
                grid_size = 50,
                kernel_basis = kernel_basis)`
the error will not occur unless you use z in `f=z~1`, which is not generalized.

Best 
steven

**Comment by andrewzm** [comment]
Hi Steven,
  1. For the invariant kernel the speed is the same everywhere yes. You can
get it from the "k" parameters in the IDE model (which correspond to the
four theta parameters in the book) through IDEmodel$get("k"). I think it's
the third and fourth parameter but check with book.

2. Sorry, currently no standard errors are provided in the package.
Obtaining them without extending the package can be done via bootstrap or
jackknife but I appreciate that will be very time consuming.

3. Yes I'm aware of that error, it's on my to-do list to fix at some point.
For now just use z. Thanks.

Regards,
Andrew

**Comment by stevenhuyi** [comment]
Thanks, Andrew. I'm looking forward to the updated version.

Best
steven
